[package]
name = "mempoolspace"
version = "0.1.0"
edition = "2024"

# TODO: add socks feature

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
url = "2.5"

[dev-dependencies]
tokio = { version = "1.46", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "mempool"
