name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        run: cargo fmt --all --check -- --config format_code_in_doc_comments=true

  check:
    name: Check crate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - -p mempoolspace
          - -p mempoolspace --features socks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        run: cargo check -p ${{ matrix.crate }}
      - name: Clippy
        run: cargo clippy -p ${{ matrix.crate }} -- -D warnings
      - name: Test
        run: cargo test -p ${{ matrix.crate }}
